import type { NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.hierarchy.insert.useQuery();

  return (
    <>
      <Head>
        <title>Employee Hierarchy App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">Hierarchy</span> Markup
          </h1>
          <div className="grid grid-cols-1">
            <div className="max-w flex max-w-xs flex-col rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">
              {data?.success
                ? data.data?.map((element, index) => (
                    <span
                      className="p-0.5"
                      style={{ marginLeft: `${element.level * 100}px` }}
                      key={`employee-${index}`}
                    >
                      {element.name}
                    </span>
                  ))
                : "Loading results..."}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
